name: divyam_excel
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_inset_box_shadow: ^1.0.8
  font_awesome_flutter: ^10.7.0
  unicons: ^2.1.1
  flextras: ^1.0.0
  flutter_localization: ^0.2.0
  expandable: ^5.0.1
  flutter_zoom_drawer: ^3.2.0
  flutter_riverpod: ^2.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/de.png
    - assets/images/de_splash.png
    - assets/images/divyam_excel.png
